language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t amray/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true amray/docker-react npm run test
