language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t amray/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true amray/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-557886792116"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
